openapi: 3.0.0
info:
  title: Your API Title
  description: API documentation for your application.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
        '401':
          description: Invalid credentials

  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request

  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: User retrieved successfully
        '404':
          description: User not found

  /providers:
    get:
      summary: Get all providers
      responses:
        '200':
          description: A list of providers
          
  /bookings:
    post:
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                roomId:
                  type: string
                checkIn:
                  type: string
                  format: date
                checkOut:
                  type: string
                  format: date
              required:
                - userId
                - roomId
                - checkIn
                - checkOut
      responses:
        '201':
          description: Booking created successfully
        '400':
          description: Bad request

  /rooms:
    get:
      summary: Get all rooms
      responses:
        '200':
          description: A list of rooms

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
    Booking:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        roomId:
          type: string
        checkIn:
          type: string
          format: date
        checkOut:
          type: string
          format: date
    Room:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        price:
          type: number
        amenities:
          type: array
          items:
            type: string
    Provider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        contact:
          type: string